project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Project"
  site-url: "https://lamahr0.github.io/MUSA550_Project-" 
  repo-url: https://github.com/lamahr0/MUSA550_Project- 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Nick Hand, 2023"

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://nickhand.dev
        text: "Personal Website"
      - icon: github
        href: https://google.com
        text: "MUSA 550 GitHub"
      - icon: twitter
        href: https://twitter.com/nicholashand
        text: "Nick Hand Twitter"         

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-python-code-blocks.qmd 
          - analysis/2-Urban-Parks-Impact.ipynb
          - analysis/3-altair-hvplot.ipynb
          - analysis/4-folium.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




