project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Project"
  site-url: "https://lamahr0.github.io/MUSA550_Project-/" 
  repo-url: https://lamahr0.github.io/MUSA550_Project-/
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; "

  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center
    tools: 
      - icon: linkedin
        href: https://www.linkedin.com/in/lama-alharbi-3b675b127/
        text: "linkedin"
      - icon: github
        href: https://github.com/lamahr0
        text: "Github"
   

    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - section: analysis/index.qmd
        contents:
          - analysis/1-Demographics_Study.ipynb
          - analysis/Estate_env.ipynb


format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




